### ISSUE TITLE
duplicated coordinates reported in the bed file

### ISSUE THREAD

**Issue by ssayols** [BiCroLab/blissNP#2]
Hi guys,
we recently detected in the files generated by this bliss pipeline, that some coordinates are duplicated (but show different number of UMIs in the 4th column). For example:
```
$ less sample1_chr-loc-countDifferentUMI.bed
<...>
1       875336  875337  1
1       875337  875338  3
1       875336  875337  2
<...>
```
and
```
$ less sample1__q60_chr-loc-strand-umi-pcr.tsv
<...>
1       875336  875337  +       TTGCCGTA        2
1       875337  875338  +       AAAAAGGG        1
1       875337  875338  +       AAATGTAC        2
1       875337  875338  +       AACCTCAG        2
1       875336  875337  -       AACTCATT        4
1       875336  875337  -       AGAACACC        3
<...>
```
The issue seems to be here for the BED file:
https://github.com/BiCroLab/blissNP/blob/1c2b9d8034854a270e1c492740dc9f2f518569ac/bin/module/umi_filter_3.sh#L6-L9
And here for the TSV file:
https://github.com/BiCroLab/blissNP/blob/1c2b9d8034854a270e1c492740dc9f2f518569ac/bin/bliss.sh#L91-L93
Looks like breaks from different strands are not aggregated to the same locus.
Any help would be appreciated.

**Comment by fagostini** [comment]
Hi,

Thanks for reaching out.

I've tried to reproduce this behaviour but in all the BED files that I've generated I couldn't find repeating coordinates. It could be a local issue due to different versions of the tools; in any case, I've just pushed a quick fix where I sort the file, ignoring the strand, before the `uniq -c`. This should solve the summarising problem.

The TSV file is actually correct: although there are repeating coordinates, they have different UMIs, which means that they derive from independent events and, therefore, cannot be attributed to PCR artefacts. You can consider the TSV file as containing DSB events rather than the unique DSB sites, which instead you can find in the BED file.

For what concerns the shift in coordinates, I believe it was made on purpose, mainly because if you use dedicated software (e.g. R, BEDtools, etc.) for the downstream analysis, functions that take into account the strand information will correctly process the coordinates. For instance, if you were to use the promoters() or flank() functions from the GenomicRanges R package to extract a single nucleotide position for each of the reads that you show in your screenshot, they would return the upstream coordinate for the reads on the plus strand and the downstream coordinate for those on the minus strand, which, in both cases, will correspond to 962201.

I hope this helps but let me know whether you have further questions.

Best regards,
Federico

**Comment by ssayols** [comment]
Hi Federico,
Many thanks for taking a look at this.

I'll double-check that this inconsistency in the BED file is not created by our toolchain. We're actually using recent versions of bedtools (2.27.1), samtools (1.10), bwa (0.7.15) and python (3.7); along with the latest version of the blissNP pipeline. Would you mind sharing with us which versions do work for you?

Actually we detected the issue with duplicated lines in the BED file in _all_ our (s)BLISS libraries. Being so widespread (for us), and you not being able to detect it, makes me suspect that the issue is in our end. 

On the other hand, please note that the problem I'm reporting is not with the duplicated lines _per se_. If you look at the figure of my previous comment, from one single DSB the BED file reports 2 different coordinates stemming from the forward and reverse strands. Also note that the BED file generated by the pipeline doesn't have strand information, so there's no way to tell apart if the 2 entries need to be aggregated or are 2 separate DSB. Therefore, the fix you suggested sorting without strand would not fix the issue.

I attach also another figure which displays a bit better our concern. In this figure, which shows multiple DSB separated by only 1bp, you will see that the shifted UMI counts (4th row) would be aggregated to the wrong DSB (2nd row).

I hope this makes the issue a bit more clear. Please let me know if you need further information.

Thanks for your help!
Sergi

![x](https://user-images.githubusercontent.com/6011316/117987487-0b07f000-b32a-11eb-8a7e-2a95357eb2ed.png)

**Comment by fagostini** [comment]
Hi Sergi,

These are the specific versions of the tools that I have in my environment:
bedtools 2.29.2 (I remember the 2.27.1 version being a bit buggy; even though this might not be the reason for the issue, I'd suggest you to update it at least to 2.28.0)
samtools 1.10-51-gf5c028b
bwa 0.7.17-r1188
python 3.8.5
In general, I'm using a conda environment to run the pipeline, and I'd reckon you could create one to test whether changing the software versions to those listed above (or even newer) solves the problem.

For what concerns the counting, you are right: the BED file does not contain the strand information and the grouping of the reads should take into account the shift. Moreover, as you are showing in the second example, this could indeed have repercussion on DSBs separated by 1bp.

I've just pushed another fix that, in addition to the coordinates sorting, replaces the `cut -f -3` with `awk '{if($4=="+"){printf "%s\t%d\t%d\n", $1, $2, $3}else{printf "%s\t%d\t%d\n", $1, $3, $3+1}}'`; the latter command leaves the reads on the forward strand untouched, but extract the correct coordinates from those on the reverse strand. This should address both issues of having similar coordinates on non-adjacent lines and not using the exact break position for different strands. 

Please bear in mind that, as you can see from your latest example, reads are usually distributed around (in our experience, they could be shifted on both sides up to 5bp) the 'real' break position. In some cases, it is not straight forward to assign them to one precise location because there can be multiple break sites very close to each other or a clear peak cannot be detected in the region. This is why the correction is not carried out within the pipeline but, if required, should to be carried out downstream in the analysis.

Let me know whether you have further questions or if you still have troubles obtaining the desired output(s).

Cheers,
Federico

**Comment by ssayols** [comment]
Hi Federico,
Many thanks for the quick response.

The last patch seems to produce the correct bed files now :-)   

Food for thought: the result is identical (at least the output bed files are) to disabling the "shifting" in the 2 scripts I mentioned at the beginning of the thread. I wonder whether a "correction for the bedtools/bamfile mismatch on negative strands end location" (as the comment in the code says) is needed at all.

But yeah as I said, the DSB loci reported by the pipeline now align to what the enzyme is supposed to do. I will in parallel test how it looks like running the pipeline within an environment with the same tool versions you suggest, to discard a problem with the tools themselves.

cheers,
Sergi
